[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"
[dependencies]
ferris-says = "0.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


